-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 4.9
-- Fri Jul 15 12:47:01 2022

-- parameterized module component declaration
component MULT
    port (Clock: in  std_logic; ClkEn: in  std_logic; 
        Aclr: in  std_logic; DataA: in  std_logic_vector(7 downto 0); 
        DataB: in  std_logic_vector(7 downto 0); 
        Result: out  std_logic_vector(15 downto 0));
end component;

-- parameterized module component instance
__ : MULT
    port map (Clock=>__, ClkEn=>__, Aclr=>__, DataA(7 downto 0)=>__, 
        DataB(7 downto 0)=>__, Result(15 downto 0)=>__);
